services:
  techathon-postgres:
    container_name: techathon-postgres
    image: "postgres:latest"
    restart: always
    ports:
      - "${POSTGRES_PORT}:5432"
    environment:
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_DB: ${POSTGRES_DB}
    volumes:
      - techathon-data:/var/lib/postgresql/data

volumes:
  techathon-data:
